ALTER TABLE public.vehicles
ADD COLUMN IF NOT EXISTS in_service BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS category TEXT,
ADD COLUMN IF NOT EXISTS color TEXT,
ADD COLUMN IF NOT EXISTS marque TEXT;
