CREATE TABLE IF NOT EXISTS public.bcs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    number TEXT NOT NULL,
    client TEXT,
    client_phone TEXT,
    amount NUMERIC,
    amount_ht NUMERIC,
    tva NUMERIC,
    tva_rate NUMERIC,
    base_ht NUMERIC,
    tva_10_amount NUMERIC,
    supplements_ht NUMERIC,
    tva_20_amount NUMERIC,
    tva_55_amount NUMERIC,
    tva_other_amount NUMERIC,
    discount_value NUMERIC,
    discount_type TEXT,
    original_ht NUMERIC,
    original_ttc NUMERIC,
    supplements_list JSONB,
    date DATE,
    status TEXT,
    type TEXT DEFAULT 'bc',
    trajet JSONB,
    driver_name TEXT,
    driver_carte_vtc TEXT,
    vehicle_name TEXT,
    vehicle_plate TEXT,
    notes TEXT,
    cgv_text TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.bcs ENABLE ROW LEVEL SECURITY;
