CREATE TABLE public.clients (
  id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id        UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  type           TEXT DEFAULT 'particulier',
  civilite       TEXT,
  nom            TEXT,
  prenom         TEXT,
  raison_sociale TEXT,
  siren          TEXT,
  tva_intra      TEXT,
  email          TEXT,
  telephone      TEXT,
  adresse        TEXT,
  code_postal    TEXT,
  ville          TEXT,
  pays           TEXT DEFAULT 'France',
  contacts       JSONB DEFAULT '[]',
  tag            TEXT,
  preferences    TEXT,
  trips          INTEGER DEFAULT 0,
  last_trip      TEXT,
  notes          TEXT,
  created_at     TIMESTAMPTZ DEFAULT now(),
  updated_at     TIMESTAMPTZ DEFAULT now()
);
